image: call9/ruby-tex:2.3

stages:
  - deploy_to_production

deploy_to_production:
  stage: update_production_branch
  script:
    - ci_tools/load_gitlab_ssh_keys.sh
    - git push -f git@beta.aptible.com:c9-production/rush-act-site.git
  allow_failure: false
  environment:
    name: production
  only:
    - master